### ISSUE TITLE
Can't "yarn add @types/audio-decode"

### ISSUE THREAD

**Issue by alexandredepape** [audiojs/audio-decode#32]
does it exists, how do you use this in a typescript project ?

**Comment by dy** [comment]
Nah, there's no types yet. You can add if you want!

**Comment by alexandredepape** [comment]
How do you make this work in a typescript project then correctly?

**Comment by dy** [comment]
```
{
  "compilerOptions": {
    "allowJs": true
  }
}
```
in _tsconfig.json_

**Comment by haouarihk** [comment]
i hacked this quick types
```ts
declare module 'audio-decode' {
  function wav(data: Buffer): Promise<AudioBuffer>;
  function mp3(data: Buffer): Promise<AudioBuffer>;
  function flac(data: Buffer): Promise<AudioBuffer>;
  function opus(data: Buffer): Promise<AudioBuffer>;
  function qoa(data: Buffer): Promise<AudioBuffer>;
  function ogg(data: Buffer): Promise<AudioBuffer>;
}
```
note: make a file called global.d.ts and put this there.
preferbly in `d` folder

**Comment by dy** [comment]
Added jsdoc. Hope it will suffice

**Comment by DaniGuardiola** [comment]
@dy I does not suffice. There are no types available, need to generate declaration files (which you should be able to do from the JSDoc you already wrote) or publish them on definitely typed. Let me know if you're looking for help here, I wouldn't mind putting up a PR.

**Comment by dy** [comment]
Sure, PR is welcomed!

**Comment by DaniGuardiola** [comment]
@dy unfortunately I won't be using this package anymore but I'm still happy to guide you though it if you want. The gist of it is that you'll need to generate `.d.ts` files with `tsc` and publish them alongside the `.js` files. In your case there's only one file you need to do that for: `audio-decode.js`. So, add typescript as a dev dependency, add a simple `.tsconfig.json` file that only includes that one file, and a `prepare` script (for example) that runs `tsc` to generate the `audio-decode.d.ts` file.

Alternatively, you could always simply maintain the types in a declaration file directly so that you don't need to generate them every time.

**Comment by dy** [comment]
Ok, added. Thanks!

**Comment by DaniGuardiola** [comment]
Glad I could help!
